<?php
$tokeni=$_POST['tokeni'];
$msg=$_POST['msg'];

function notify($to,$data){

    $api_key="AAAAgQVMLiE:APA91bG-OszIG4VfKvtJ6eHON7W3brRhp6mghsEfQSJRXLxr8L4R1CR4vWMIN82qR5BePqCblbVTuGXS09uoKq_wGH6gISTT9bJOuE1KwFJfJ7ekxmKY-wolSxmYgD0-1zqDAIjv6guZ";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

$to=$tokeni;
$data=array(
    'title'=>'new MESSAGE',
    'body'=>"$msg"
);

notify($to,$data);
echo "Notification Sent";

?>